/* Curso de Andrea Rocca · CC BY-NC-SA 4.0. M4 no modifica la producción de M3. */
(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const sample='data:image/svg+xml;charset=utf-8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="640" height="360" viewBox="0 0 640 360"><rect width="640" height="360" fill="#e8f3e8"/><circle cx="510" cy="80" r="40" fill="#f4ba5a"/><path d="M265 230h110l-20 95h-70z" fill="#b86b46"/><path d="M320 235V90" stroke="#28633d" stroke-width="12"/><ellipse cx="282" cy="155" rx="45" ry="22" fill="#4f945a" transform="rotate(25 282 155)"/><ellipse cx="357" cy="120" rx="45" ry="22" fill="#28633d" transform="rotate(-25 357 120)"/></svg>');
  const imageExample='<img src="'+sample+'" alt="Planta de hojas verdes en una maceta" style="width:50%;height:auto">';
  const starter='<!DOCTYPE html>\n<html lang="es">\n<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Mi proyecto</title></head>\n<body>\n<h1>Mi proyecto</h1>\n<p>Contá qué ofrecés y para quién.</p>\n<h2>Qué ofrecemos</h2>\n<ul><li>Una propuesta</li><li>Otra propuesta</li><li>Una tercera propuesta</li></ul>\n<h2>Cómo participar</h2>\n<p>Explicá cómo puede participar quien visita tu página.</p>\n<a href="https://andrearocca.github.io/CursoHTML/" target="_blank" rel="noopener noreferrer">Conocer el curso</a>\n</body>\n</html>';
  const lessons=[
    {title:'Una imagen que también se puede comprender',text:'img incorpora una imagen y no lleva etiqueta de cierre. src indica dónde encontrarla; alt describe su contenido o función para quien no puede verla. Para una imagen informativa, escribí una descripción útil. Una imagen decorativa puede usar alt vacío, pero en esta misión trabajamos con una imagen informativa.',code:'<img src="DIRECCION_DE_LA_IMAGEN" alt="Planta de hojas verdes en una maceta" style="width:50%;height:auto">',more:'Para un porcentaje usamos CSS dentro de style: width:50%;height:auto. El atributo HTML width admite un número de píxeles, por ejemplo width="320". CSS indica apariencia; img, ol y strong aportan estructura o significado.'},
    {title:'Una secuencia necesita orden',text:'ul agrupa elementos cuyo orden no es esencial. ol indica una lista ordenada: pasos para pedir, inscribirse o participar. Cada elemento se escribe con li dentro de la lista.',code:'<ol>\n  <li>Elegir una propuesta</li>\n  <li>Realizar el pedido</li>\n  <li>Coordinar la entrega</li>\n</ol>',more:'Elegí ol porque el orden tiene sentido, no solamente para que aparezcan números.'},
    {title:'Destacar lo importante',text:'strong señala importancia. El navegador suele mostrarlo en negrita, pero su función no es simplemente decorar. Elegí una frase que el visitante necesite reconocer.',code:'<p>La inscripción es <strong>gratuita</strong>.</p>',more:'No hace falta destacar todo el párrafo. Si todo está destacado, cuesta distinguir la información principal.'},
    {title:'Color para comunicar',text:'style es un atributo HTML. Dentro escribimos declaraciones de CSS: una propiedad, dos puntos, un valor y punto y coma. Probá un color que se pueda leer sobre el fondo.',code:'<h1 style="color:purple;">Taller Verde</h1>',more:'Cambiar color no cambia la importancia de un título. Evitá depender solamente del color para comunicar información.'},
    {title:'Tipografía y combinación de estilos',text:'font-family elige una familia tipográfica. Si la primera no está disponible, el navegador puede usar la alternativa. Combiná color y tipografía dentro de un único atributo style.',code:'<h2 style="color:darkgreen;font-family:Georgia,serif;">Nuestras propuestas</h2>',more:'También podés probar Arial,sans-serif o Verdana,sans-serif. Buscá legibilidad y coherencia con tu proyecto.'}
  ];
  const repairs=[
    {title:'El color no cambia',goal:'Martina quiere un título de color violeta. Corregí la declaración de CSS.',code:'<h1 style="color=purple">Taller Verde</h1>',hint:'Una declaración usa dos puntos: color:purple;',solution:'<h1 style="color:purple;">Taller Verde</h1>'},
    {title:'Una imagen sin descripción',goal:'La imagen se ve, pero falta una descripción útil. Agregá alt sin cambiar la imagen.',code:'<img src="'+sample+'" style="width:50%;height:auto">',hint:'Usá alt="..." para explicar qué muestra la imagen: una planta en una maceta.',solution:imageExample},
    {title:'Los pasos tienen un orden',goal:'Convertí estos pasos en una lista ordenada. Conservá sus dos elementos.',code:'<ul><li>Elegir</li><li>Confirmar</li></ul>',hint:'Cambiá el contenedor ul por ol tanto en la apertura como en el cierre.',solution:'<ol><li>Elegir</li><li>Confirmar</li></ol>'},
    {title:'Una palabra importante',goal:'Señalá la importancia de la palabra gratuita usando strong. Conservá el resto del párrafo.',code:'<p>La inscripción es gratuita.</p>',hint:'Encerrá solamente gratuita entre <strong> y </strong>.',solution:'<p>La inscripción es <strong>gratuita</strong>.</p>'},
    {title:'Elegir una tipografía',goal:'Aplicá Georgia al título de sección sin perder su color verde.',code:'<h2 style="color:darkgreen;letra:Georgia;">Nuestras propuestas</h2>',hint:'La propiedad para la familia tipográfica es font-family.',solution:'<h2 style="color:darkgreen;font-family:Georgia,serif;">Nuestras propuestas</h2>'}
  ];
  function fresh(){return {fields:{},code:starter,originalCode:starter,repairCode:repairs.map(r=>r.code),attempts:repairs.map(()=>[]),hints:repairs.map(()=>0),repairSolved:repairs.map(()=>false),repairSolutions:repairs.map(()=>false),lesson:0};}
  if(!state.moduleFour||typeof state.moduleFour!=='object'||Array.isArray(state.moduleFour))state.moduleFour=fresh();
  let work=state.moduleFour;
  const defaults=fresh();
  for(const [key,value] of Object.entries(defaults)){if(Array.isArray(value)){if(!Array.isArray(work[key]))work[key]=value;work[key]=value.map((v,i)=>work[key][i]??v);}else if(typeof work[key]!==typeof value||work[key]===null)work[key]=value;}
  if(Array.isArray(work.fields))work.fields={};
  work.attempts=work.attempts.map(a=>Array.isArray(a)?a:[]);
  work.lesson=Math.max(0,Math.min(4,Number(work.lesson)||0));
  function save(){try{persist();document.querySelectorAll('.m4-save').forEach(e=>e.textContent='✓ Guardado en este navegador. Entregá el PDF del módulo 4 en Classroom.');}catch{document.querySelectorAll('.m4-save').forEach(e=>e.textContent='No pudimos guardar. Conservá el HTML y el PDF antes de salir.');}}
  const status='<p class="mini-status m4-save" role="status"></p>';
  const field=(id,label)=>'<label for="'+id+'">'+label+'</label><textarea data-m4-field id="'+id+'"></textarea>';
  const head=(part,title,text)=>'<div class="section-head"><div><div class="eyebrow">Módulo 4 · '+part+'</div><h2>'+title+'</h2><p>'+text+'</p></div></div>';
  $('module4').innerHTML=head('Aprender y reparar','Mejoramos nuestra página','Retomá tu proyecto: hoy sumamos imágenes, una lista ordenada, información importante y primeros estilos.')+
    '<div class="lesson"><article class="card"><h3>El nuevo encargo de Martina</h3><p>Su página ya comunica una propuesta. Ahora necesita mostrar una imagen, ordenar los pasos para participar y destacar lo importante. Primero probá cinco recursos; después usalos en tu propia página. No hace falta empezar de cero.</p><div class="m3-route"><span>Observar</span><span>Comprender</span><span>Reparar</span><span>Mejorar</span><span>Probar</span><span>Reflexionar</span><span>PDF del módulo 4</span></div><label for="m4Name">Nombre y apellido</label><input class="student-name" data-m4-field id="m4Name" autocomplete="name"><p>En una computadora compartida, revisá que este trabajo sea tuyo.</p><button class="btn ghost" id="m4New">Empezar como otro estudiante</button>'+status+'</article>'+
    '<article class="card"><h3 id="m4LessonTitle"></h3><p id="m4LessonText"></p><pre class="m3-code" id="m4LessonCode"></pre><p class="m4-note" id="m4LessonMore"></p><div class="actions"><button class="btn ghost" id="m4Prev">← Anterior</button><span id="m4LessonCount"></span><button class="btn" id="m4Next">Siguiente recurso →</button></div></article>'+
    '<article class="card"><h3>Probá el tamaño de la imagen</h3><p>Mové el control y observá cómo cambia. La altura se mantiene proporcional.</p><div class="m4-meter"><label for="m4Width">Ancho</label><input type="range" id="m4Width" min="30" max="100" value="50" step="10"><output id="m4WidthValue">50%</output></div><pre class="m3-code" id="m4WidthCode"></pre><iframe id="m4SizePreview" class="m3-preview m3-mini-preview" sandbox="" title="Prueba del ancho de una imagen"></iframe>'+field('m4Observe','¿Qué cambió al variar el porcentaje? ¿Qué tamaño elegirías y por qué?')+'</article>'+
    '<article class="card"><h3>Elegir la dirección de una imagen</h3><p>Usá una imagen propia o con permiso de reutilización. “Copiar dirección de imagen” no es lo mismo que copiar la dirección de la página. Probala en una pestaña nueva y registrá su fuente. La dirección puede dejar de funcionar si el sitio la cambia o impide mostrarla en otras páginas.</p><p>Para practicar sin conexión tenés una ilustración incluida de una planta en una maceta. Su dirección es larga porque contiene la imagen dentro del código.</p><details><summary>¿Y una imagen propia en Drive?</summary><p>Un enlace para compartir un archivo de Drive no garantiza que se pueda insertar como imagen. Probá el acceso sin tu sesión y comprobá la imagen dentro de la página. Si no funciona, usá la imagen de práctica o una dirección directa válida. No necesitás cambiar permisos ni publicar archivos para realizar la práctica.</p></details></article>'+
    '<article class="card" id="m4Repairs"><h3>Rescatá las mejoras de Martina</h3><p>Escribí cada reparación y probala. Podés usar pistas o consultar una solución; no se descuentan puntos.</p><p id="m4RepairScore" role="status"></p>'+
    repairs.map((r,i)=>'<section><h3>Misión '+(i+1)+' · '+r.title+'</h3><p>'+r.goal+'</p><label for="m4Repair'+i+'">Código a reparar</label><textarea class="m3-editor m3-repair" id="m4Repair'+i+'" spellcheck="false"></textarea><div class="actions"><button class="btn" data-m4-check="'+i+'">Probar reparación</button><button class="btn ghost" data-m4-hint="'+i+'">Necesito una pista</button><button class="btn ghost" data-m4-solution="'+i+'">Ver una solución</button></div><p class="feedback" id="m4Feedback'+i+'" role="status"></p></section>').join('')+
    field('m4Explain','Elegí una reparación y explicá por qué tu cambio resuelve el problema.')+'</article><div class="actions"><button class="btn ok" id="m4ToWorkshop">Mejorar mi página →</button></div></div>';
  $('module4Workshop').innerHTML=head('Crear y probar','Cinco recursos para tu proyecto','Conservá el contenido del módulo 3 y agregá recursos que ayuden a tus visitantes.')+
    '<div class="lesson"><article class="card"><h3>Recuperá tu código</h3><p>Si tu trabajo está en otra computadora, recuperá el HTML de Classroom o de tu versión compartida en YachayCodex y pegalo en el editor. Si está en este navegador, podés copiarlo con el botón. Esto no modifica el trabajo guardado del módulo 3.</p><div class="actions"><button class="btn ghost" id="m4Import">Copiar mi código del módulo 3</button><button class="btn ghost" id="m4Baseline">Guardar el código pegado como punto de partida</button><button class="btn ghost" id="m4Sample">Copiar etiqueta de imagen de práctica</button></div><p id="m4ImportStatus" role="status"></p><label for="m4SampleCode">Etiqueta disponible para copiar manualmente</label><textarea id="m4SampleCode" readonly class="m3-editor m3-repair"></textarea>'+field('m4Project','¿Cuál es tu proyecto y qué querés mejorar?')+'</article>'+
    '<article class="card"><h3>Tu mesa de trabajo</h3><ul><li>Una imagen informativa con src y alt útiles.</li><li>Una lista ordenada ol con sus elementos li.</li><li>Información importante marcada con strong.</li><li>Un texto con otro color mediante style.</li><li>Un cambio de tipografía mediante font-family.</li></ul><p>Combiná color y tipografía en un mismo elemento y explicá qué mejora aporta. Revisá que el texto siga siendo legible.</p><div class="m3-split"><div><label for="m4Code">Tu HTML completo o el contenido de body</label><textarea id="m4Code" class="m3-editor" spellcheck="false"></textarea></div><div><p class="m3-preview-caption">Vista previa de tu página</p><iframe id="m4Preview" class="m3-preview" sandbox="" title="Vista previa del módulo 4"></iframe></div></div><div class="actions"><button class="btn" id="m4Check">Actualizar vista y revisar recursos</button><button class="btn ghost" id="m4Download">Descargar mi HTML</button><button class="btn ghost" id="m4CopyBody">Copiar contenido de body</button></div><p id="m4CodeStatus" role="status"></p><ul id="m4Checks" class="m3-checklist"></ul><p>La revisión detecta elementos y declaraciones, no evalúa toda la sintaxis ni garantiza que una imagen externa cargue. Los enlaces de esta vista no navegan; probá la versión compartida por separado.</p>'+status+'</article>'+
    '<article class="card"><h3>Probar con otra persona</h3>'+field('m4Source','Fuente de la imagen: enlace o “ilustración de práctica del curso”, autoría y permiso si corresponde.')+field('m4Peer','¿Qué entendió tu compañero? ¿Pudo ver la imagen, seguir los pasos y leer el texto?')+field('m4Change','¿Qué cambiaste después de probar? Explicá también dónde combinaste color y tipografía.')+'<label><input type="checkbox" data-m4-field id="m4ImageSeen"> Comprobé que se ve la imagen en la versión final.</label><label><input type="checkbox" data-m4-field id="m4Readable"> Revisamos la legibilidad y el orden de los pasos.</label></article>'+
    '<div class="actions"><button class="btn ghost" id="m4Back">← Volver a los recursos</button><button class="btn ok" id="m4ToClose">Reflexión y PDF del módulo 4 →</button></div></div>';
  $('module4Close').innerHTML=head('Reflexionar y entregar','Entrega del Módulo 4','Guardá un PDF propio de este módulo. No reemplaza los PDF de los módulos 1, 2 y 3.')+
    '<div class="lesson"><article class="card"><h3>Tu versión final</h3><p>Si trabajaste en YachayCodex, pegá primero tu HTML final en el taller del curso para que el PDF incluya la misma versión. Compartí y probá el enlace con otra persona, como en el módulo 3. También podés adjuntar el HTML junto con el PDF, sin usar un editor externo.</p><label for="m4DeliveryType">¿Cómo entregás la página?</label><select data-m4-field id="m4DeliveryType"><option value="">Elegí una modalidad</option><option value="file">Archivo HTML + PDF en Classroom</option><option value="link">Enlace a mi versión compartida + PDF</option></select><label for="m4Url">Enlace a tu trabajo, si corresponde</label><input class="student-name" data-m4-field id="m4Url" type="url"><label><input type="checkbox" data-m4-field id="m4LinkTested"> Probé el enlace sin mi sesión.</label>'+field('m4ShareProblem','¿Tuviste alguna dificultad para recuperar, mostrar o compartir tu página?')+'</article>'+
    '<article class="card"><h3>Lo que aprendiste y lo que falta revisar</h3>'+field('m4Reflect1','1. ¿Qué diferencia hay entre src y alt?')+field('m4Reflect2','2. ¿Cuándo usarías ol en lugar de ul?')+field('m4Reflect3','3. ¿Qué significado aporta strong?')+field('m4Reflect4','4. ¿Qué parte de tu código es HTML y qué parte es CSS? Explicá un ejemplo.')+field('m4Reflect5','5. ¿Qué error corregiste y qué pregunta te quedó?')+'<label for="m4Confidence">Semáforo de aprendizaje</label><select data-m4-field id="m4Confidence"><option value="">Elegí una opción</option><option>Verde: puedo explicarlo</option><option>Amarillo: necesito practicar</option><option>Rojo: necesito ayuda</option></select></article>'+
    '<article class="card"><h3>Un módulo, un PDF</h3><p>Prepará el informe, elegí Guardar como PDF en la impresión y adjuntalo en la tarea del módulo 4 de Classroom. Si usás la modalidad de archivo, adjuntá también tu HTML. Abrir el informe no realiza la entrega.</p><div class="actions"><button class="btn ghost" id="m4BackWorkshop">← Revisar mi página</button><button class="btn ok" id="m4Report">Preparar PDF del Módulo 4</button><button class="btn ghost" id="m4DownloadFinal">Descargar HTML final</button></div><p id="m4ReportStatus" role="status"></p>'+status+'</article></div>';
  function parse(code){return new DOMParser().parseFromString(code,'text/html');}
  function validImage(src){return src===sample||/^data:image\/(?:png|jpeg|gif|webp);base64,[a-z0-9+/=\s]+$/i.test(src)||safeURL(src)?.protocol==='https:';}
  function safeURL(s){try{const u=new URL(s);return /^https?:$/.test(u.protocol)&&!u.username&&!u.password?u:null;}catch{return null;}}
  function preview(id,code){
    const doc=parse(code);
    doc.querySelectorAll('script,iframe,object,embed,link,base,meta,style,svg,math,form,input,button,video,audio,source').forEach(e=>e.remove());
    const allowed=new Set(['H1','H2','H3','H4','P','UL','OL','LI','STRONG','EM','B','I','IMG','A','DIV','SPAN','SECTION','ARTICLE','HEADER','FOOTER','BR','HR','PRE','CODE','FIGURE','FIGCAPTION']);
    doc.body.querySelectorAll('*').forEach(e=>{
      if(!allowed.has(e.tagName)){e.replaceWith(...e.childNodes);return;}
      const src=e.getAttribute('src')||'',alt=e.getAttribute('alt'),color=e.style.color,font=e.style.fontFamily,width=e.style.width,height=e.style.height;
      [...e.attributes].forEach(a=>e.removeAttribute(a.name));
      if(e.tagName==='IMG'){if(validImage(src))e.setAttribute('src',src);if(alt!==null)e.setAttribute('alt',alt);e.setAttribute('referrerpolicy','no-referrer');}
      if(color)e.style.color=color;if(font)e.style.fontFamily=font;if(/^\d+(?:\.\d+)?(?:%|px)$/.test(width))e.style.width=width;if(height==='auto')e.style.height=height;
    });
    $(id).srcdoc='<!doctype html><html lang="es"><head><meta charset="UTF-8"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; img-src https: data:; style-src \'unsafe-inline\'; form-action \'none\'; base-uri \'none\'"><style>body{padding:12px;font:16px/1.5 system-ui;overflow-wrap:anywhere}img{max-width:100%}pre{white-space:pre-wrap}</style></head><body>'+doc.body.innerHTML+'</body></html>';
  }
  function inspect(code){
    const d=parse(code),text=e=>!!e?.textContent.trim(),styled=[...d.body.querySelectorAll('[style]')];
    const rows=[
      [[...d.querySelectorAll('img')].some(e=>validImage(e.getAttribute('src')||'')&&!!e.getAttribute('alt')?.trim()),'Imagen con dirección admitida y descripción alt; comprobar visualmente su carga.'],
      [[...d.querySelectorAll('ol')].some(e=>[...e.children].filter(c=>c.tagName==='LI'&&text(c)).length>=2),'Lista ordenada con al menos dos pasos.'],
      [[...d.querySelectorAll('strong')].some(text),'Información importante con strong.'],
      [styled.some(e=>text(e)&&!!e.style.color),'Texto con una declaración de color válida.'],
      [styled.some(e=>text(e)&&!!e.style.fontFamily),'Texto con font-family.'],
      [styled.some(e=>text(e)&&e.style.color&&e.style.fontFamily),'Color y tipografía combinados en el mismo elemento.']
    ];return {rows,score:rows.filter(r=>r[0]).length,total:rows.length};
  }
  function repairValid(i,code){const d=parse(code);
    if(i===0)return d.querySelector('h1')?.style.color==='purple'&&d.querySelector('h1').textContent.trim()==='Taller Verde';
    if(i===1)return [...d.querySelectorAll('img')].some(e=>e.getAttribute('src')===sample&&(e.getAttribute('alt')||'').trim().length>=8);
    if(i===2){const list=d.querySelector('ol');return list&&[...list.children].filter(e=>e.tagName==='LI').map(e=>e.textContent.trim()).join('|')==='Elegir|Confirmar';}
    if(i===3)return d.querySelector('strong')?.textContent.trim()==='gratuita'&&d.querySelector('p')?.textContent.trim()==='La inscripción es gratuita.';
    const h=d.querySelector('h2');return !!h&&/georgia/i.test(h.style.fontFamily)&&h.style.color==='darkgreen'&&h.textContent.trim()==='Nuestras propuestas';
  }
  function collect(){document.querySelectorAll('[data-m4-field]').forEach(e=>work.fields[e.id]=e.type==='checkbox'?e.checked:e.value);work.code=$('m4Code').value;repairs.forEach((_,i)=>work.repairCode[i]=$('m4Repair'+i).value);}
  function score(){$('m4RepairScore').textContent=work.repairSolved.filter(Boolean).length+'/5 reparaciones resueltas · reintentos sin penalización';}
  function showLesson(){const l=lessons[work.lesson];$('m4LessonTitle').textContent=l.title;$('m4LessonText').textContent=l.text;$('m4LessonCode').textContent=l.code;$('m4LessonMore').textContent=l.more;$('m4LessonCount').textContent=(work.lesson+1)+' de 5';$('m4Prev').disabled=work.lesson===0;$('m4Next').textContent=work.lesson===4?'Ir a las reparaciones ↓':'Siguiente recurso →';}
  function checks(){collect();const result=inspect(work.code);$('m4Checks').replaceChildren();result.rows.forEach(([ok,label])=>{const li=document.createElement('li');li.className=ok?'ok':'bad';li.textContent=(ok?'✓ Detectado: ':'○ Para revisar: ')+label;$('m4Checks').append(li);});preview('m4Preview',work.code);save();return result;}
  function move(id){collect();save();go(id);}
  function bind(id,fn){$(id).addEventListener('click',fn);}
  function download(){collect();save();const blob=new Blob([work.code],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='modulo4.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function copy(text,statusId){try{await navigator.clipboard.writeText(text);$(statusId).textContent='Código copiado.';}catch{$(statusId).textContent='No se pudo copiar automáticamente. Seleccioná y copiá el código del cuadro.';}}
  function workURL(){const u=safeURL(work.fields.m4Url||'');if(!u||['localhost','127.0.0.1','0.0.0.0'].includes(u.hostname))return null;if(u.hostname==='andrearocca.github.io'&&u.pathname.replace(/\/$/,'')==='/CursoHTML')return null;if(u.hostname==='yachaycodex.dev'||(u.hostname==='app.yachaycodex.dev'&&/^\/(?:shared\/?)?$/.test(u.pathname)))return null;return u.href;}
  function report(){
    collect();save();const f=work.fields,st=$('m4ReportStatus'),name=(f.m4Name||'').trim();
    if(!name){st.textContent='Escribí tu nombre al comienzo del módulo.';go('module4');$('m4Name').focus();return;}
    if(!['file','link'].includes(f.m4DeliveryType)){st.textContent='Elegí si entregás HTML adjunto o enlace junto con el PDF.';return;}
    const link=f.m4DeliveryType==='link'?workURL():null;
    if(f.m4DeliveryType==='link'&&!link){st.textContent='Pegá el enlace completo a tu trabajo compartido, no el editor vacío ni la dirección del curso.';return;}
    const result=inspect(work.code),answer=id=>String(f[id]||'').trim()||'(Sin respuesta)';
    const reflectionIds=['m4Reflect1','m4Reflect2','m4Reflect3','m4Reflect4','m4Reflect5'];
    const pending=[];if(['m4Observe','m4Project','m4Explain','m4Confidence'].some(id=>!f[id]?.trim()))pending.push('Observación, proyecto o explicación');if(work.repairSolved.some(v=>!v))pending.push('Reparaciones');if(result.score<result.total)pending.push('Recursos de la página');if(reflectionIds.some(id=>!f[id]?.trim()))pending.push('Reflexiones');if(!f.m4Peer?.trim()||!f.m4Change?.trim()||!f.m4ImageSeen||!f.m4Readable)pending.push('Prueba y mejora');if(!f.m4Source?.trim())pending.push('Fuente de la imagen');
    const lines=['DISEÑAR PARA LA WEB — ENTREGA DEL MÓDULO 4','Mejoramos nuestra página · Tecnología · 4.º año','Estudiante: '+name,'Fecha: '+new Date().toLocaleString('es-AR'),pending.length?'Actividad incompleta · Pendiente: '+pending.join(', '):'Actividades registradas; requieren revisión docente.','Entrega independiente: no incluye respuestas de otros módulos.','','1. OBSERVACIÓN Y PROYECTO',answer('m4Observe'),answer('m4Project'),'','2. REPARACIONES Y PROCESO'];
    repairs.forEach((r,i)=>{lines.push('Misión '+(i+1)+' · '+r.title,'Estado actual: '+(work.repairSolved[i]?'resuelta':'pendiente')+'; intentos: '+work.attempts[i].length+'; pistas: '+work.hints[i]+'; solución consultada: '+(work.repairSolutions[i]?'sí':'no'),'Respuesta final:',work.repairCode[i]);work.attempts[i].forEach((a,j)=>lines.push('Intento '+(j+1)+' · '+a.date+' · '+(a.correct?'correcto':'a revisar'),a.code,'Devolución: '+a.feedback));});
    lines.push('Explicación de una reparación:',answer('m4Explain'),'','3. REVISIÓN ORIENTATIVA',result.score+'/'+result.total+' criterios detectados; no es una nota ni una validación completa.',...result.rows.map(([ok,label])=>(ok?'Detectado: ':'Para revisar: ')+label),'','4. PRUEBA Y MEJORA','Fuente de la imagen:',answer('m4Source'),'Prueba con otra persona:',answer('m4Peer'),'Mejora y combinación de estilos:',answer('m4Change'),'Declara que comprobó la imagen: '+(f.m4ImageSeen?'sí':'no'),'Declara revisión de legibilidad y pasos: '+(f.m4Readable?'sí':'no'),'','5. REFLEXIÓN',...reflectionIds.map((id,i)=>(i+1)+'. '+['Diferencia entre src y alt:','Cuándo usar ol en lugar de ul:','Significado de strong:','HTML y CSS en mi código:','Error corregido y pregunta pendiente:'][i]+' '+answer(id)),'Semáforo: '+answer('m4Confidence'),'','6. ENTREGA',link?'Enlace: '+link:'Se adjunta modulo4.html junto a este PDF en Classroom.','Declara prueba sin su cuenta: '+(f.m4LinkTested?'sí':'no')+'. El curso no verifica acceso externo.',answer('m4ShareProblem'),'','7. CÓDIGO HTML FINAL',work.code,'','8. CÓDIGO DE PARTIDA — PLANTILLA O COPIA RECUPERADA',work.originalCode,'','Los intentos y ayudas no descuentan puntos. Entregar este PDF en la tarea del módulo 4 de Classroom.','Curso creado por Andrea Rocca · CC BY-NC-SA 4.0');
    if(openWorkReport('CursoHTML_Modulo4_'+name,lines.join('\n'),st,link)){if(!pending.length&&!state.done.includes('module4'))state.done.push('module4');if(pending.length)state.done=state.done.filter(id=>id!=='module4');save();window.courseDelivery?.prepared(4);}
  }
  document.querySelectorAll('[data-m4-field]').forEach(e=>{if(e.type==='checkbox')e.checked=!!work.fields[e.id];else e.value=work.fields[e.id]||'';e.addEventListener(e.tagName==='SELECT'||e.type==='checkbox'?'change':'input',()=>{collect();save();});});
  $('m4Code').value=work.code;$('m4SampleCode').value=imageExample;
  $('m4Code').addEventListener('input',()=>{collect();$('m4Checks').textContent='Código modificado: actualizá la vista y la revisión.';save();});
  repairs.forEach((r,i)=>{$('m4Repair'+i).value=work.repairCode[i];work.repairSolved[i]=!!work.repairSolved[i]&&!!repairValid(i,work.repairCode[i]);$('m4Repair'+i).addEventListener('input',()=>{collect();work.repairSolved[i]=false;score();save();});});
  document.querySelectorAll('[data-m4-check]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.m4Check);collect();const ok=!!repairValid(i,work.repairCode[i]),feedback=ok?'La reparación cumple el objetivo. Explicá qué cambiaste.':repairs[i].hint;work.repairSolved[i]=ok;work.attempts[i].push({date:new Date().toISOString(),code:work.repairCode[i],correct:ok,feedback});$('m4Feedback'+i).textContent=feedback;$('m4Feedback'+i).className='feedback show '+(ok?'ok':'');score();save();});
  document.querySelectorAll('[data-m4-hint]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.m4Hint);work.hints[i]++;$('m4Feedback'+i).textContent=repairs[i].hint;$('m4Feedback'+i).className='feedback show';save();});
  document.querySelectorAll('[data-m4-solution]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.m4Solution);work.repairSolutions[i]=true;$('m4Feedback'+i).textContent='Una solución posible:\n'+repairs[i].solution+'\nAhora escribila vos y probala.';$('m4Feedback'+i).className='feedback show';save();});
  function size(){const width=$('m4Width').value;$('m4WidthValue').textContent=width+'%';$('m4WidthCode').textContent='style="width:'+width+'%;height:auto"';preview('m4SizePreview',imageExample.replace('width:50%','width:'+width+'%'));}
  $('m4Width').oninput=size;
  bind('m4Prev',()=>{work.lesson--;showLesson();save();});bind('m4Next',()=>{if(work.lesson<4){work.lesson++;showLesson();save();}else $('m4Repairs').scrollIntoView({block:'start',behavior:'smooth'});});
  bind('m4ToWorkshop',()=>move('module4Workshop'));bind('m4Back',()=>move('module4'));bind('m4ToClose',()=>{checks();move('module4Close');});bind('m4BackWorkshop',()=>move('module4Workshop'));
  bind('m4Import',()=>{const code=state.moduleThree?.code;if(typeof code!=='string'||!code.trim()){$('m4ImportStatus').textContent='No hay código del módulo 3 en este navegador. Recuperalo de tu archivo o enlace y pegalo en el editor.';return;}if(work.code!==starter&&!confirm('¿Reemplazar el código del módulo 4 por una copia del módulo 3? Descargá antes tu versión actual.'))return;work.originalCode=code;work.code=code;$('m4Code').value=code;checks();$('m4ImportStatus').textContent='Código copiado. El módulo 3 conserva su versión.';});
  bind('m4Baseline',()=>{collect();if(confirm('¿Registrar el código actual como la versión de partida para comparar las mejoras?')){work.originalCode=work.code;save();$('m4ImportStatus').textContent='Versión de partida registrada.';}});
  bind('m4Sample',()=>copy(imageExample,'m4ImportStatus'));bind('m4CopyBody',()=>{collect();copy(parse(work.code).body.innerHTML,'m4CodeStatus');});bind('m4Check',checks);bind('m4Download',download);bind('m4DownloadFinal',download);bind('m4Report',report);
  bind('m4New',()=>{if(confirm('¿Borrar únicamente el trabajo del módulo 4? Conservá antes su HTML y PDF.')){state.moduleFour=fresh();state.done=state.done.filter(id=>id!=='module4');if(state.moduleDeliveries)delete state.moduleDeliveries[4];save();location.reload();}});
  showLesson();score();size();preview('m4Preview',work.code);save();
  if(location.hash==='#module4')go('module4');
})();
