// Ejecutar con Node y Playwright. QA local del Módulo 5; no publica datos.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const target=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname.replace(/^\/$/,'/index.html')));if(!target.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}fs.readFile(target,(e,data)=>{if(e){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',target.endsWith('.js')?'application/javascript':target.endsWith('.css')?'text/css':'text/html');res.end(data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;let browser;try{
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe'});const context=await browser.newContext({viewport:{width:1366,height:900},acceptDownloads:true});await context.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);
 assert.equal(await page.locator('#nav button').count(),10);const ids=await page.locator('[id]').evaluateAll(es=>es.map(e=>e.id));assert.equal(ids.length,new Set(ids).size);
 await page.click('#nav-module5');if(await page.locator('#deliveryGuard').isVisible())await page.getByRole('button',{name:'Sí, continuar',exact:true}).click();assert.equal(await page.locator('#module5').isVisible(),true);await page.fill('#m5Name','Estudiante QA');
 const solutions=['<iframe src="https://www.youtube-nocookie.com/embed/j6eHyUBweyE" title="¿Qué es una página web?"></iframe>','<iframe src="https://www.youtube-nocookie.com/embed/j6eHyUBweyE" title="Presentación del proyecto"></iframe>','<main><section><h2>Nuestra propuesta</h2><p>Una idea de Martina.</p></section></main>','<video controls><source src="presentacion.mp4" type="video/mp4">Tu navegador no puede reproducir el video.</video>'];
 for(let i=0;i<4;i++){await page.fill('#m5Repair'+i,solutions[i]);await page.click('[data-m5-check="'+i+'"]');}assert.match(await page.textContent('#m5RepairScore'),/4\/4/);await page.fill('#m5StructureExplain','La estructura comunica la función de cada parte.');await page.fill('#m5RepairExplain','Cambié la URL por una dirección embed válida.');
 await page.click('#m5ToWorkshop');const layout=await page.evaluate(()=>{const e=document.getElementById('m5Code').getBoundingClientRect(),p=document.getElementById('m5Preview').getBoundingClientRect();return{ew:e.width,cw:document.querySelector('#module5Workshop .card').getBoundingClientRect().width,eh:e.height,pt:p.top,eb:e.bottom};});assert.ok(layout.ew>=layout.cw-42);assert.ok(layout.eh>=630);assert.ok(layout.pt>=layout.eb);
 const code='<!doctype html><html><body><header><h1>Proyecto QA</h1></header><nav><a href="#propuesta">Propuesta</a><a href="#video">Video</a></nav><main><section id="propuesta"><h2>Propuesta</h2><p>Presentamos nuestro proyecto para toda la comunidad escolar.</p></section><section id="video"><h2>Video</h2><iframe src="https://www.youtube-nocookie.com/embed/j6eHyUBweyE" title="Presentación del proyecto"></iframe><p>En este video explicamos qué hacemos, para quién y cómo participar.</p></section></main><footer><p>Proyecto escolar</p></footer></body></html>';
 await page.fill('#m5Code',code);await page.click('#m5Check');assert.equal(await page.locator('#m5Checks .ok').count(),9);await page.reload();await page.click('#nav-module5');if(await page.locator('#deliveryGuard').isVisible())await page.getByRole('button',{name:'Sí, continuar',exact:true}).click();await page.click('#m5ToWorkshop');assert.equal(await page.inputValue('#m5Code'),code);
 const d=page.waitForEvent('download');await page.click('#m5Download');assert.equal((await d).suggestedFilename(),'modulo5.html');
 await page.fill('#m5Plan','El video explica el proyecto y el resumen conserva la idea central.');await page.fill('#m5VideoSource','Video de Andrea Rocca, YouTube.');await page.fill('#m5Peer','Comprendió el tema sin reproducirlo y encontró las secciones.');await page.fill('#m5Change','Agregué un resumen más claro.');await page.check('#m5NoAutoplay');await page.check('#m5Controls');await page.click('#m5ToClose');await page.selectOption('#m5DeliveryType','file');for(let i=1;i<=5;i++)await page.fill('#m5Reflect'+i,'Respuesta reflexiva '+i);await page.selectOption('#m5Confidence',{index:1});
 const popup=page.waitForEvent('popup');await page.click('#m5Report');const report=await popup;await report.waitForLoadState();const text=await report.textContent('pre');assert.match(text,/ENTREGA DEL MÓDULO 5/);assert.ok(text.includes(code));assert.ok(!text.includes('Actividad incompleta'));await report.close();assert.match(await page.locator('#module5Close [data-delivery-status="5"]').textContent(),/Informe abierto/);
 for(const width of [390,320]){await page.setViewportSize({width,height:844});for(const screen of ['module5','module5Workshop','module5Close','deliveries']){await page.evaluate(id=>go(id),screen);if(await page.locator('#deliveryGuard').isVisible())await page.getByRole('button',{name:'Sí, continuar',exact:true}).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Sin overflow '+screen+' '+width);}}
 assert.deepEqual(errors,[]);console.log('OK: módulo 5, navegación, misiones, editor ampliado, revisión, persistencia, HTML, PDF independiente y móvil.');await context.close();
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
